### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by Brick0810** [Brick0810/The-Bankers#2]
System allows a user to login and access their account

**Comment by Daniel-Monjezi** [comment]
Both the login and sign up pages have been implemented as well as working perfectly fine.

Notes on the login/sign up system:
-There are multiple checks put in place for when someone signs up: Empty fields, already used userID, incorrect email format, password and repeat password does not match
-When a user signs in successfully, the website will change, allowing them to access private pages (such as accounts page, transactions etc) that they couldn't see before 
-Users details are stored on a mySQL database when they sign up as well as data being retrieved from the database whenever a user tries to sign in 
-When a user signs in and signs up, the password is hashed which means a hacker can not access/see the password and enhances the security drastically
